@baseUrl = http://localhost:3000/api/users

### Đăng ký tài khoản (Register)
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "daoquanghau2003@gmail.com",
    "password": "Hau12345",
    "name": "Hậu"
}

### Đăng nhập (Login)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "daoquanghau@gmail.com",
    "password": "Hau12345"
}

### Lấy thông tin người dùng (Me)
GET {{baseUrl}}/me
Authorization: Bearer {{login.response.body.token}}

### Cập nhật thông tin cá nhân (Update Profile)
PUT {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "name": "Hậu Updated",
    "is_deleted": "0",
    "avatar": "null"
}
